### ISSUE TITLE
this vin number is not valid but it is valid?

### ISSUE THREAD

**Issue by lidyum** [idlesign/vininfo#11] opened 2021-08-07 07:40 UTC
W1V44770513858498

Manufacturer: Mercedes-Benz
Model: 911

**Comment by idlesign** [comment] 2021-08-21 01:58
`verify_checksum()` method descritpion says: _Not every manufacturer uses VIN checksum rules._
For example check digit is compulsory for Nort America and China but not for Europe.

**Comment by idlesign** [comment] 2021-08-21 02:05
I've update WMI database in `master` so now `Mercedes-Benz` should be detected correcly for this and similar numbers.

**Comment by lidyum** [comment] 2021-08-29 19:01
tnhx. But version number is still 1.5.1?

**Comment by idlesign** [comment] 2021-08-30 12:57
New version 1.6.0 is now available on PyPI. Cheers.

Closing this one. 
Feel free to reopen if the issue is relevant for the latest version.

**Closed by idlesign** 2021-08-30 12:57 UTC
Labels: question
